dist: trusty
language: c
compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
      - build-essential bzip2 gzip git libreadline-dev libpq-dev postgresql-server-dev-all libcurl4-openssl-dev libnl-3-dev libnl-genl-3-dev libnl-nf-3-dev libnl-route-3-dev libxml2-dev libevent-dev libfuse-dev libjson-c-dev

services:
  - postgresql

before_script:
  - psql -c 'CREATE USER "cloudgw-tests";' -U postgres
  - psql -c "CREATE DATABASE \"cloudgw-tests\" WITH TEMPLATE template0 OWNER=\"cloudgw-tests\" ENCODING='UTF8';" -U postgres
  - psql -U "cloudgw-tests" "cloudgw-tests" < "src/scripts/create_pg_database.sql"

script:
  ### build libevaio
  - wget https://bitbucket.org/rgacogne/libevaio/get/libevaio_0_4.tar.bz2
  - tar xjf libevaio_0_4.tar.bz2
  - cd rgacogne-libevaio-36c968b3ad5f
  - mkdir build
  - cd build
  - cmake ..
  - make
  - cd ../..
  ### build Cloud Gateway
  - mkdir build
  - cd build
  - CFLAGS="${CFLAGS} -I${TRAVIS_BUILD_DIR}/rgacogne-libevaio-36c968b3ad5f/src/" LDFLAGS="${LDFLAGS} -L${TRAVIS_BUILD_DIR}/rgacogne-libevaio-36c968b3ad5f/build/src/lib/"  cmake ../src
  - make
  ### prepare test environment:
  - dd if=/dev/urandom of=/tmp/small.data bs=1M count=1
  - dd if=/dev/urandom of=/tmp/huge.data bs=1M count=100
  - LD_LIBRARY_PATH="${TRAVIS_BUILD_DIR}/rgacogne-libevaio-36c968b3ad5f/build/src/lib/" CG_TESTS_LOCAL_PROVIDERS_ONLY=true CTEST_OUTPUT_ON_FAILURE=TRUE make test

